on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket ${{ matrix.racket-variant }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.13
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: current
          dest: '"${HOME}/racketdist-${{ matrix.racket-variant }}"'
          local_catalogs: $GITHUB_WORKSPACE
          sudo: never

      - run: |
          raco pkg install -i --auto --no-setup --skip-installed scribble-test
          raco pkg update --auto --no-setup scribble-text-lib scribble-html-lib scribble-lib scribble-doc scribble-test

      # This uses --pkgs so that we don't have to figure out which collections
      # each package adds modules to.
      - run: raco setup --check-pkg-deps --pkgs scribble-text-lib scribble-html-lib scribble-lib scribble-doc scribble-test

      # Tests are run with --drdr to help keep racket's CI systems consistent
      # with each other.
      - run: raco test --drdr --package scribble-text-lib scribble-html-lib scribble-lib scribble-doc scribble-test
